version: "3.8"
services:
  app:
    container_name: salmon_stats_app
    build:
      context: ./app
    ports:
      - 3000:3000

  nginx:
    container_name: salmon_stats_server
    image: nginx:1.21.6
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
      - 8080:8080
