version: "3.8"
services:
  db:
    image: postgres:14.2
    container_name: salmon_stats_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # migration:
  #   container_name: salmon_stats_migration
  #   build:
  #     context: ./app
  #   ports:
  #     - $PRISMA_STUDIO_PORT:$PRISMA_STUDIO_PORT
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   command: [sh, -c, yarn prisma generate, yarn prisma migrate deploy]

  app:
    container_name: salmon_stats_app
    build:
      context: ./app
    ports:
      - 3000:3000
    # depends_on:
    #   migration:
    #     condition: service_completed_successfully
    command:
      [
        sh,
        -c,
        yarn prisma migrate dev --name init && yarn build && yarn start:prod,
      ]

  studio:
    container_name: salmon_stats_studio
    build:
      context: ./app
    ports:
      - 5555:5555
    # depends_on:
    #   migration:
    #     condition: service_completed_successfully
    command: [sh, -c, yarn prisma studio]

  hash:
    container_name: salmon_stats_hash
    build:
      context: ./hash
    # depends_on:
    #   migration:
    #     condition: service_completed_successfully
    ports:
      - 3001:3001

  nginx:
    container_name: salmon_stats_server
    image: nginx:1.21.6
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
      - 8080:8080
